/* ============================================================
   STORE — the live, editable project list
   ------------------------------------------------------------
   The site's real source of truth is the browser's localStorage,
   not js/data.js. The first time the site runs in a browser, it
   copies DEFAULT_PROJECTS into storage. From then on, every page
   reads through the functions below, and the Admin page
   (admin.html) writes through them too.

   This means: no server, no build step, and you can add/edit/
   delete projects — including ones you haven't built yet — any
   time from the Admin page. The trade-off: it lives in ONE
   browser. Use "Export data.js" on the Admin page whenever you
   want to save your changes permanently (e.g. before clearing
   browser data, or to move them to another computer/repo).
   ============================================================ */

const STORAGE_KEY = "hanan_portfolio_projects_v1";

function loadProjects(){
  const raw = localStorage.getItem(STORAGE_KEY);
  if (raw){
    try {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed;
    } catch (e){ /* fall through and reseed */ }
  }
  const seed = (typeof DEFAULT_PROJECTS !== "undefined") ? DEFAULT_PROJECTS : [];
  saveProjects(seed);
  return seed;
}

function saveProjects(list){
  localStorage.setItem(STORAGE_KEY, JSON.stringify(list));
}

function slugify(str){
  return String(str || "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "project";
}

function uniqueId(base, list, excludeId){
  let id = slugify(base);
  let candidate = id;
  let n = 2;
  const taken = new Set(list.filter(p => p.id !== excludeId).map(p => p.id));
  while (taken.has(candidate)){
    candidate = `${id}-${n}`;
    n++;
  }
  return candidate;
}

function addProject(project){
  const list = loadProjects();
  if (!project.id) project.id = uniqueId(project.title, list);
  else project.id = uniqueId(project.id, list);
  list.push(project);
  saveProjects(list);
  return project;
}

function updateProject(originalId, updated){
  const list = loadProjects();
  const idx = list.findIndex(p => p.id === originalId);
  if (idx === -1) return null;
  updated.id = updated.id ? uniqueId(updated.id, list, originalId) : originalId;
  list[idx] = updated;
  saveProjects(list);
  return updated;
}

function deleteProject(id){
  const list = loadProjects().filter(p => p.id !== id);
  saveProjects(list);
}

function resetToDefaults(){
  saveProjects(typeof DEFAULT_PROJECTS !== "undefined" ? DEFAULT_PROJECTS : []);
}

function exportAsJson(){
  return JSON.stringify(loadProjects(), null, 2);
}

function exportAsDataJsSource(){
  const json = JSON.stringify(loadProjects(), null, 2);
  return `/* Generated by the Admin page — export of your live project data.
   Replace the contents of js/data.js with this file (keep the file name
   js/data.js) to make your current changes the new permanent default. */

const DEFAULT_PROJECTS = ${json};
`;
}

function importFromJson(jsonText){
  const parsed = JSON.parse(jsonText);
  if (!Array.isArray(parsed)) throw new Error("Expected a JSON array of projects.");
  saveProjects(parsed);
  return parsed;
}

function downloadTextFile(filename, text){
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
